version: '3'
services:
  app:
    image: test-agitext-image
    ports:
      - "8282:8282"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/basics?allowPublicKeyRetrieval=true
    depends_on:
      - db
  db:
    image: test-agitext-image
    ports:
      - "3306:3307"
    networks:
      - springapimysql-net
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clientdb
      MYSQL_PASSWORD: root
networks:
  springapimysql-net:
